### ISSUE TITLE
Back Button does't work properly on version 0.0.49

### ISSUE THREAD

**Issue by andreapesci** [Mortafix/AutoConv-Telegram-Python#3]
FIRST ERROR: 
stopping the Bot while in a state with back button enabled will cause an exception when restarted the bot by pressing the back button.

```
Exception:
'NoneType' object has no attribute 'name'

Traceback:
  File "C:\Users\Andrea\Dev\Python\telegram_bots\channel_manager\venv\lib\site-packages\autoconv\autoconv_handler.py", line 359, in manage_conversation
    state = self._change_state(typed_data)
  File "C:\Users\Andrea\Dev\Python\telegram_bots\channel_manager\venv\lib\site-packages\autoconv\autoconv_handler.py", line 92, in _change_state
    {"prev_state": self.prev_state.name, "state": new_state.name}
```

SECOND ERROR:
True raises AttributeError.

```
Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    from states import STATE, autoconv, errore
  File "C:\Users\Andrea\Dev\Python\telegram_bots\channel_manager\states.py", line 76, in <module>
    bit.add_routes(wip, default=menu, back=True)
  File "pydantic\decorator.py", line 52, in pydantic.decorator.validate_arguments.validate.wrapper_function
    """
  File "pydantic\decorator.py", line 145, in pydantic.decorator.ValidatedFunction.call
    names = set([name] + [arg.strip(' *') for arg in
  File "pydantic\decorator.py", line 142, in pydantic.decorator.ValidatedFunction.init_model_instance
    if mo is None:
  File "pydantic\main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AddRoutes
back
  instance of State expected (type=type_error.arbitrary_type; expected_arbitrary_type=State)
```

**Comment by Mortafix** [comment]
Version `0.0.50` is out with a fix, try to upgrade and hope for the best!
